### ISSUE TITLE
Documentation efforts

### ISSUE THREAD

**Issue by 4www** [hellerve/zepto#14]
- [x] stdlib
- [ ] few macros aren't 
- [ ] list
- [ ] vector
- [ ] hashmap
- [ ] string

**Comment by hellerve** [comment]
Thanks for the issue. I am currently focused on documenting the primitives in zepto itself, but we should definitely not lose track of that.

On another note: could we perhaps move this issue to the zepto-stdlib repository, as this is the repo that needs to be fixed?

**Comment by 4www** [comment]
-> moved to https://github.com/zepto-lang/zepto-stdlib/issues/3
